### ISSUE TITLE
Request for Multiarch Build Support

### ISSUE THREAD

**Issue by csabca83** [mobilecoinofficial/gha-runner#18]
## Description:

Hello,

I’ve noticed that the current builds of gha-runner are only available for AMD-based CPUs. With the increasing use of ARM-based computing environments, it would be highly beneficial to have support for these architectures as well.

## Request:

Could you please consider adding support for ARM-based architectures in addition to the existing AMD builds? Multiarch support would significantly increase the usability and accessibility of the gha-runner project for a broader range of devices.

## Additional Information:

Current Architecture Support: AMD (x86_64)
Requested Additional Architectures: ARM (e.g., armv7, arm64)
Thank you for considering this enhancement. If there are any specific requirements or steps I can assist with to facilitate this addition, please let me know.

**Comment by jgreat** [comment]
@csabca83 Thanks for the sample PR. We will consider adding an ARM container to the artifacts.

**Comment by csabca83** [comment]
Thanks @jgreat

**Comment by jgreat** [comment]
Support added in #24 

Thanks for your contribution!
